import { responsiveFontSize, responsiveHeight, responsiveWidth } from "@/utils/responsive.js"
import { StyleSheet } from "react-native"
export  const Otpstyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#FFFFFF",
      paddingHorizontal: responsiveWidth(20),
      paddingTop: responsiveHeight(20),
      alignItems: "center",
      position: "relative",
    },
    backButton: {
      position: "absolute",
      top: responsiveHeight(15),
      left: responsiveWidth(15),
    },
    backButtonCircle: {
      backgroundColor: "#F5F5F5",
      width: responsiveHeight(40),
      height: responsiveHeight(40),
      borderRadius: responsiveWidth(20),
      alignItems: "center",
      justifyContent: "center",
    },
    logo: {
      position: "absolute",
      width: responsiveWidth(172.62),
      height: responsiveHeight(237),
      top: responsiveHeight(55),
      left: responsiveWidth(100.69),
    },
    titleAndSubtitleContainer: {
      position: "absolute",
      height: responsiveHeight(60),
      width: responsiveWidth(274),
      top: responsiveHeight(342),
      left: responsiveWidth(50),
  
      gap: responsiveHeight(5),
    },
    title: {
      fontFamily: "Font-Bold",
      // height:responsiveHeight(15),
      fontSize: responsiveFontSize(20),
      lineHeight: responsiveFontSize(28),
      fontWeight: "700",
      color: "#24364C",
      textAlign: "center",
    },
    phoneText: {
      justifyContent: "center",
      // alignItems:'center',
      flexDirection: "row",
      flexWrap: "wrap",
      textAlign: "center",
  
      width: "100%",
      height: responsiveHeight(30),
    },
    authCodeText: {
      color: "#5F729D",
      fontFamily: "Font-Medium",
      fontSize: responsiveFontSize(14),
      fontWeight: "500",
      lineHeight: responsiveHeight(20),
    },
    phoneNumber: {
      fontFamily: "Font-Medium",
      fontSize: responsiveFontSize(14),
      fontWeight: "500",
      color: "#FE5120",
      lineHeight: responsiveHeight(20),
    },
    otpWrapper: {
      position: "absolute",
      width: responsiveWidth(252),
      height: responsiveHeight(94),
      left: responsiveWidth(61),
      top: responsiveHeight(432),
      gap: responsiveHeight(10),
    },
    otpContainer: {
      flexDirection: "row",
      alignSelf: "center",
      width: responsiveWidth(222),
      justifyContent: "space-between",
    },
    otpSlot: {
      backgroundColor: "#F5F7FA",
      width: responsiveWidth(48),
      height: responsiveWidth(48),
      borderRadius: responsiveWidth(6),
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: "#E5E7EB",
    },
    otpSlotActive: {
      borderColor: "#E5E7EB",
      borderWidth: 1,
    },
    otpSlotText: {
      fontFamily: "Font-Medium",
      fontSize: responsiveFontSize(28),
      lineHeight: responsiveFontSize(32),
      fontWeight: "300",
      color: "#000000",
      textAlign: "center",
      textTransform: "capitalize",
    },
    caret: {
      width: responsiveWidth(2),
      height: responsiveHeight(20),
      backgroundColor: "#6D028E",
    },
    resendContainer: {
      alignItems: "center",
      width: "100%",
    },
    resendInfo: {
      fontFamily: "Font-Medium",
      fontSize: responsiveFontSize(16),
      lineHeight: responsiveFontSize(24),
      fontWeight: "500",
      color: "#5F729D",
      textAlign: "center",
    },
    resendLink: {
      fontFamily: "Font-Medium",
      fontSize: responsiveFontSize(16),
      lineHeight: responsiveFontSize(24),
      fontWeight: "600",
      color: "#FE5120",
      textAlign: "center",
    },
    verifyButton: {
      position: "absolute",
      top: responsiveHeight(748),
      width: responsiveWidth(315),
      height: responsiveHeight(48),
      backgroundColor: "#6D028E",
      borderRadius: responsiveWidth(8),
      justifyContent: "center",
      left: responsiveWidth(30),
    },
    verifyButtonText: {
      fontFamily: "Font-Bold",
      fontSize: responsiveFontSize(15),
      fontWeight: "700",
      color: "#FFFFFF",
      textAlign: "center",
      textTransform: "capitalize",
      lineHeight: responsiveFontSize(15),
    },
    SiginInContainer: {
      position: "absolute",
      top: responsiveHeight(800),
      textAlign: "center",
    },
    signInText: {
      color: "purple",
      fontFamily: "Font-Medium",
      fontSize: responsiveFontSize(14),
      fontWeight: "500",
      lineHeight: responsiveHeight(20),
    },
    signInLink: {
      color: "#FE5120",
      textDecorationLine: "underline",
    },
  })
  